# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
alias(
    name = "basic",
    actual = "//src/orchestration:basic",
    visibility = ["//visibility:public"],
)

alias(
    name = "main_macro_basic",
    actual = "//src/orchestration:main_macro_basic",
    visibility = ["//visibility:public"],
)

alias(
    name = "branching",
    actual = "//src/orchestration:branching",
    visibility = ["//visibility:public"],
)

alias(
    name = "catch_error",
    actual = "//src/orchestration:catch_error",
    visibility = ["//visibility:public"],
)

alias(
    name = "dag",
    actual = "//src/orchestration:dag",
    visibility = ["//visibility:public"],
)

alias(
    name = "events_across_local_programs",
    actual = "//src/orchestration:events_across_local_programs",
    visibility = ["//visibility:public"],
)

alias(
    name = "shutdown",
    actual = "//src/orchestration:shutdown",
    visibility = ["//visibility:public"],
)

alias(
    name = "shutdown_using_signals",
    actual = "//src/orchestration:shutdown_using_signals",
    visibility = ["//visibility:public"],
)

alias(
    name = "inter_process_event_sender",
    actual = "//src/orchestration:inter_process_event_sender",
    visibility = ["//visibility:public"],
)

alias(
    name = "inter_process_event_receiver",
    actual = "//src/orchestration:inter_process_event_receiver",
    visibility = ["//visibility:public"],
)

alias(
    name = "camera_drv_object_det",
    actual = "//src/orchestration/examples/camera_drv_object_det:camera_drv_object_det",
    visibility = ["//visibility:public"],
)
